image: circleci/android:api-29

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle

stages:
  - build
  - lint
  - test

# Default configuration inherited by other jobs.
.default: &default
  tags:
    - docker, halcyon

build:
  <<: *default
  stage: build
  script:
    - ./gradlew assemble
    - ./gradlew podspec
  only:
    - master
    - /^release.*$/
    - merge_requests
  artifacts:
    paths:
      - app/build/outputs/apk/debug/
    expire_in: 1 days

test:
  <<: *default
  stage: test
  script:
    - ./gradlew test
  only:
    - master
    - develop
    - /^release.*$/
    - merge_requests
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml

lint:
  <<: *default
  stage: lint
  before_script: [ ]
  script:
    - ./gradlew lint
  only:
    - master
    - develop
    - /^release.*$/
    - merge_requests
  artifacts:
    paths:
      - /build/reports/lint-results.html
    expire_in: 5 days