# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

use_frameworks!

target 'App Portfolio (iOS)' do
  pod 'common', :path => '../common/'
  pod 'Kingfisher/SwiftUI', '~> 5.15.7'
end

target 'App Portfolio (macOS)' do
  pod 'common', :path => '../common/'
  pod 'Kingfisher/SwiftUI', '~> 5.15.7'
end
